//
//  RDCollectionView.h
//  HappyUIKit
//
//  Created by Roman Dzieciol on 1/27/17.
//  Copyright © 2017 RDI. All rights reserved.
//

#import <UIKit/UIKit.h>

@class RDCollectionViewData;
@class UIFocusContainerGuide;
@class RDCollectionViewCell;
@class RDCollectionViewUpdate;
@class _RDCollectionViewPrefetchingContext;
@class _UIDynamicAnimationGroup;
@class _UIVelocityIntegrator;
@class _UIFeedbackDragSnappingBehavior;
@protocol RDCollectionViewDataSourcePrefetching;
@protocol RDCollectionViewDataSource;
@protocol RDCollectionViewDelegate;
@class RDCollectionReusableView;
@class RDCollectionViewLayout;
@class RDCollectionViewLayoutAttributes;

@protocol RDCollectionViewDataSource_Private <NSObject>


@end

@protocol _UIKeyboardAutoRespondingScrollView
@end

@interface RDCollectionView : UIScrollView {
//@interface RDCollectionView : UIScrollView <_UIKeyboardAutoRespondingScrollView> {
    NSTimer * _autoscrollTimer;
    UIView * _backgroundView;
    NSMutableDictionary * _cellClassDict;
    NSMutableDictionary * _cellNibDict;
    NSMutableDictionary * _cellNibExternalObjectsTables;
    NSMutableDictionary * _cellReuseQueues;
    NSMutableDictionary * _clonedCellsDict;
    NSMutableDictionary * _clonedDecorationViewsDict;
    NSMutableDictionary * _clonedSupplementaryViewsDict;
    RDCollectionViewData * _collectionViewData;
    struct {
        unsigned int delegateShouldHighlightItemAtIndexPath : 1;
        unsigned int delegateDidHighlightItemAtIndexPath : 1;
        unsigned int delegateDidUnhighlightItemAtIndexPath : 1;
        unsigned int delegateShouldSelectItemAtIndexPath : 1;
        unsigned int delegateShouldDeselectItemAtIndexPath : 1;
        unsigned int delegateDidSelectItemAtIndexPath : 1;
        unsigned int delegateDidDeselectItemAtIndexPath : 1;
        unsigned int delegateSupportsMenus : 1;
        unsigned int delegateWillDisplayCell : 1;
        unsigned int delegateWillDisplaySupplementaryView : 1;
        unsigned int delegateDidEndDisplayingCell : 1;
        unsigned int delegateDidEndDisplayingSupplementaryView : 1;
        unsigned int delegateIndexForReferenceItemDuringLayoutTransition : 1;
        unsigned int delegateOverrideForTransitionOffsetSize : 1;
        unsigned int delegateTargetContentOffsetForProposedContentOffsetSPI : 1;
        unsigned int delegateTargetContentOffsetForProposedContentOffset : 1;
        unsigned int delegateTargetIndexPathForMoveSPI : 1;
        unsigned int delegateTargetIndexPathForMove : 1;
        unsigned int delegateCanFocusItemAtIndexPath_deprecated : 1;
        unsigned int delegateDidFocusItemAtIndexPath_deprecated : 1;
        unsigned int delegateCanFocusItemAtIndexPath : 1;
        unsigned int delegateDidFocusItemAtIndexPath : 1;
        unsigned int delegateDidUnfocusItemAtIndexPath : 1;
        unsigned int delegateShouldChangeFocusedItem : 1;
        unsigned int delegateIndexPathForPreferredFocusedItem : 1;
        unsigned int delegateShouldUpdateFocusFromRowAtIndexPathToView : 1;
        unsigned int delegateIndexPathForPreferredFocusedView : 1;
        unsigned int delegateShouldUpdateFocusInContext : 1;
        unsigned int delegateDidUpdateFocusInContext : 1;
        unsigned int delegateTemplateLayoutCell : 1;
        unsigned int delegateWillLayoutCellUsingTemplateLayoutCell : 1;
        unsigned int delegateWasNonNil : 1;
        unsigned int dataSourceNumberOfSections : 1;
        unsigned int dataSourceViewForSupplementaryElement : 1;
        unsigned int dataSourceCanMoveItemAtIndexPathSPI : 1;
        unsigned int dataSourceMoveItemAtIndexPathSPI : 1;
        unsigned int dataSourceCanMoveItemAtIndexPath : 1;
        unsigned int dataSourceMoveItemAtIndexPath : 1;
        unsigned int dataSourceWasNonNil : 1;
        unsigned int prefetchDataSourcePrefetchItemsAtIndexPaths : 1;
        unsigned int prefetchDataSourceCancelPrefetchingForItemsAtIndexPaths : 1;
        unsigned int prefetchDataSourceWasNonNil : 1;
        unsigned int reloadSkippedDuringSuspension : 1;
        unsigned int scheduledUpdateVisibleCells : 1;
        unsigned int scheduledUpdateVisibleCellLayoutAttributes : 1;
        unsigned int allowsSelection : 1;
        unsigned int allowsMultipleSelection : 1;
        unsigned int allowsSelectionDuringEditing : 1;
        unsigned int allowsMultipleSelectionDuringEditing : 1;
        unsigned int fadeCellsForBoundsChange : 1;
        unsigned int updatingLayout : 1;
        unsigned int needsReload : 1;
        unsigned int reloading : 1;
        unsigned int skipLayoutDuringSnapshotting : 1;
        unsigned int layoutInvalidatedSinceLastCellUpdate : 1;
        unsigned int doneFirstLayout : 1;
        unsigned int loadingOffscreenViews : 1;
        unsigned int updating : 1;
        unsigned int updatingVisibleCells : 1;
        unsigned int preRotationBoundsSet : 1;
        unsigned int updateFocusAfterItemAnimations : 1;
        unsigned int remembersLastFocusedIndexPath : 1;
        unsigned int updateFocusAfterLoadingCells : 1;
        unsigned int performingLayout : 1;
        unsigned int keepsFirstResponderVisibleOnBoundsChange : 1;
        unsigned int inCreateTemplateCell : 1;
        unsigned int editing : 1;
        unsigned int shouldDeriveVisibleBoundsFromContainingScrollView : 1;
        unsigned int usingCustomLayoutMargins : 1;
        unsigned int settingDefaultLayoutMargins : 1;
        unsigned int shouldPrefetchCellsWhenPerformingReloadData : 1;
        unsigned int scheduledReloadPrefetchDuringNextLayoutPass : 1;
    }  _collectionViewFlags;
    NSInteger  _containerScrollViewVisitationCount;
    UIFocusContainerGuide * _contentFocusContainerGuide;
    CGPoint  _currentCenterOffset;
    double  _currentInteractiveTransitionProgress;
    double  _currentInteractiveTransitionTimeStamp;
    _RDCollectionViewPrefetchingContext * _currentPrefetchingContext;
    RDCollectionViewCell * _currentPromiseFulfillmentCell;
    UITouch * _currentTouch;
    RDCollectionViewUpdate * _currentUpdate;
    id<RDCollectionViewDataSource_Private>  _dataSource;
    NSMutableDictionary * _dataSourceToLayoutIndexPathMappingDict;
    UIEdgeInsets  _defaultLayoutMargins;
    NSMutableArray * _deleteItems;
    _UIDynamicAnimationGroup * _endInteractiveTransitionAnimationGroup;
    UIFocusContainerGuide * _endOfContentFocusContainerGuide;
    NSIndexPath * _firstResponderIndexPath;
    RDCollectionReusableView * _firstResponderView;
    NSString * _firstResponderViewKind;
    NSInteger  _firstResponderViewType;
    RDCollectionReusableView * _focusedCell;
    NSString * _focusedCellElementKind;
    NSIndexPath * _focusedCellIndexPath;
    NSInteger  _focusedViewType;
    NSMutableSet * _indexPathsForHighlightedItems;
    NSMutableSet * _indexPathsForSelectedItems;
    NSMutableArray * _insertItems;
    id /* block */  _interactiveCompletionHandler;
    NSMutableDictionary * _interactiveTransitionInfos;
    NSMutableDictionary * _interactiveTransitionValueTrackingDict;
    NSMutableDictionary * _invalidatedDecorationIndexPaths;
    NSMutableSet * _invalidatedItemIndexPaths;
    NSMutableDictionary * _invalidatedSupplementaryIndexPaths;
    id /* block */  _invalidationBlock;
    bool  _isInInteractiveTransition;
    CGPoint  _lastLayoutOffset;
    RDCollectionViewLayout * _layout;
    NSMutableArray * _moveItems;
    id /* block */  _navigationCompletion;
    UIView * _newContentView;
    RDCollectionViewLayout * _nextLayoutForInteractiveTranstion;
    NSArray * _originalDeleteItems;
    NSArray * _originalInsertItems;
    NSMutableSet * _pendingDeselectionIndexPaths;
    NSIndexPath * _pendingSelectionIndexPath;
    id /* block */  _postUpdateBlock;
    CGRect  _preRotationBounds;
    NSMutableDictionary * _prefetchCacheItems;
    id<RDCollectionViewDataSourcePrefetching> _prefetchDataSource;
    NSInteger  _prefetchMode;
    _UIVelocityIntegrator * _prefetchVelocityIntegrator;
    bool  _prefetchingEnabled;
    CGPoint  _previousCenterOffset;
    double  _previousInteractiveTransitionProgress;
    double  _previousInteractiveTransitionTimeStamp;
    NSMutableArray * _reloadItems;
    NSInteger  _reloadingSuspendedCount;
    _UIFeedbackDragSnappingBehavior * _reorderFeedbackBehavior;
    NSMutableArray * _reorderedItems;
    CGPoint  _reorderingTargetPosition;
    NSInteger  _rotationAnimationCount;
    CGPoint  _rotationBoundsOffset;
    bool  _shouldAccumulateTrackedLayoutValues;
    double  _startTimeStamp;
    NSMutableDictionary * _supplementaryViewClassDict;
    NSMutableDictionary * _supplementaryViewNibDict;
    NSMutableDictionary * _supplementaryViewNibExternalObjectsTables;
    NSMutableSet * _supplementaryViewRegisteredKinds;
    NSMutableDictionary * _supplementaryViewReuseQueues;
    NSMutableDictionary * _templateLayoutCells;
    NSMutableArray * _trackedValuesKeys;
    RDCollectionViewLayoutAttributes * _transitionLayoutAttributes;
    NSInteger  _updateAnimationCount;
    id /* block */  _updateCompletionHandler;
    NSInteger  _updateCount;
    CGRect  _visibleBounds;
    NSMutableDictionary * _visibleCellsDict;
    NSMutableDictionary * _visibleDecorationViewsDict;
    NSMutableDictionary * _visibleSupplementaryViewsDict;
}

@property (getter=_isEditing, nonatomic, readonly) bool _editing;
@property (getter=_allowsEffectiveMultipleSelection, nonatomic, readonly) bool allowsEffectiveMultipleSelection;
@property (getter=_allowsEffectiveSelection, nonatomic, readonly) bool allowsEffectiveSelection;
@property (nonatomic) bool allowsMultipleSelection;
@property (nonatomic) bool allowsSelection;
@property (nonatomic, retain) UIView *backgroundView;
@property (getter=_collectionViewData, nonatomic, readonly) RDCollectionViewData *collectionViewData;
@property (nonatomic, retain) RDCollectionViewLayout *collectionViewLayout;
@property (getter=_currentPromiseFulfillmentCell, setter=_setCurrentPromiseFulfillmentCell:, nonatomic, retain) RDCollectionViewCell *currentPromiseFulfillmentCell;
@property (getter=_currentTouch, setter=_setCurrentTouch:, nonatomic, retain) UITouch *currentTouch;
@property (getter=_currentUpdate, nonatomic, readonly) RDCollectionViewUpdate *currentUpdate;
@property (nonatomic) id<RDCollectionViewDataSource_Private> dataSource;
@property (getter=_dataSourceSupportsReordering, nonatomic, readonly) bool dataSourceSupportsReordering;
@property (readonly, copy) NSString *debugDescription;
@property (getter=_defaultLayoutMargins, setter=_setDefaultLayoutMargins:, nonatomic) UIEdgeInsets defaultLayoutMargins;
@property (nonatomic) id<RDCollectionViewDelegate> delegate;
@property (readonly, copy) NSString *description;
@property (getter=_endOfContentFocusContainerGuide, nonatomic, readonly) UIFocusContainerGuide *endOfContentFocusContainerGuide;
@property (getter=_focusedCell, setter=_setFocusedCell:, nonatomic, retain) RDCollectionReusableView *focusedCell;
@property (getter=_focusedCellElementKind, setter=_setFocusedCellElementKind:, nonatomic, copy) NSString *focusedCellElementKind;
@property (getter=_focusedCellIndexPath, setter=_setFocusedCellIndexPath:, nonatomic, copy) NSIndexPath *focusedCellIndexPath;
@property (readonly) NSUInteger hash;
@property (nonatomic, readonly, nullable) NSArray<NSIndexPath *> *indexPathsForSelectedItems;
@property (nonatomic, readonly) NSArray *indexPathsForVisibleItems;
@property (getter=_keepsFirstResponderVisibleOnBoundsChange, setter=_setKeepsFirstResponderVisibleOnBoundsChange:, nonatomic) bool keepsFirstResponderVisibleOnBoundsChange;
@property (getter=_navigationCompletion, setter=_setNavigationCompletion:, nonatomic, copy) id /* block */ navigationCompletion;
@property (nonatomic, readonly) NSInteger numberOfSections;
@property (nonatomic) id<RDCollectionViewDataSourcePrefetching> prefetchDataSource;
@property (getter=isPrefetchingEnabled, nonatomic) bool prefetchingEnabled;
@property (nonatomic) bool remembersLastFocusedIndexPath;
@property (getter=_reorderedItems, nonatomic, readonly) NSArray *reorderedItems;
@property (getter=_reorderingTargetPosition, nonatomic, readonly) CGPoint reorderingTargetPosition;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSArray *visibleCells;
@property (getter=_visibleViews, nonatomic, readonly) NSArray *visibleViews;

// Image: /System/Library/Frameworks/UIKit.framework/UIKit

+ (id)_reuseKeyForSupplementaryViewOfKind:(id)arg1 withReuseIdentifier:(id)arg2;

//- (void).cxx_destruct;
- (void)_addContainerScrollViewForNotifications:(id)arg1;
- (void)_addControlledSubview:(id)arg1 atZIndex:(NSInteger)arg2;
- (void)_addEntriesFromDictionary:(id)arg1 inDictionary:(id)arg2;
- (void)_addEntriesFromDictionary:(id)arg1 inDictionary:(id)arg2 andSet:(id)arg3;
- (void)_adjustForAutomaticKeyboardInfo:(id)arg1 animated:(bool)arg2 lastAdjustment:(double*)arg3;
- (bool)_allowsEffectiveMultipleSelection;
- (bool)_allowsEffectiveSelection;
- (bool)_allowsMultipleSelectionDuringEditing;
- (bool)_allowsSelectionDuringEditing;
- (void)_applyBlockToAllReusableViews:(id /* block */)arg1;
- (void)_applyLayoutAttributes:(id)arg1 toView:(id)arg2;
- (id)_arrayForUpdateAction:(int)arg1;
- (void)_autoscrollForReordering:(id)arg1;
- (bool)_beginReorderingItemAtIndexPath:(id)arg1;
- (void)_beginUpdates;
- (bool)_canEditItemAtIndexPath:(id)arg1;
- (bool)_canPerformAction:(SEL)arg1 forCell:(id)arg2 sender:(id)arg3;
- (bool)_canReorderItemAtIndexPath:(id)arg1;
- (void)_cancelInteractiveTransitionWithFinalAnimation:(bool)arg1;
- (void)_cancelReordering;
- (void)_cancelTouches;
- (void)_cellBecameFocused:(id)arg1;
- (bool)_cellCanBecomeFocused:(id)arg1;
- (void)_cellDidBecomeFocused:(id)arg1;
- (void)_cellDidBecomeUnfocused:(id)arg1;
- (id)_cellForItemAtIndexPath:(id)arg1 includePrefetchedCells:(bool)arg2;
- (void)_cellMenuDismissed;
- (NSInteger)_cellPrefetchMode;
- (void)_checkForPreferredAttributesInView:(id)arg1 originalAttributes:(id)arg2;
- (id)_childFocusRegionsInRect:(CGRect)arg1;
- (void)_cleanUpAfterInteractiveTransitionDidFinish:(bool)arg1;
- (id)_collectionViewData;
- (void)_completeInteractiveMovementWithDisposition:(NSInteger)arg1;
- (CGRect)_computeFutureVisibleBoundsForPrefetchVelocity:(struct CGVector { double x1; double x2; })arg1 visibleBounds:(CGRect)arg2;
- (CGRect)_computePrefetchCacheValidationBoundsForPrefetchVelocity:(struct CGVector { double x1; double x2; })arg1 visibleBounds:(CGRect)arg2;
- (void)_computePrefetchCandidatesForVelocity:(struct CGVector { double x1; double x2; })arg1 notifyDelegateIfNeeded:(bool)arg2;
- (void)_computePrefetchCandidatesForVisibleBounds:(CGRect)arg1 futureVisibleBounds:(CGRect)arg2 prefetchVector:(struct CGVector { double x1; double x2; })arg3 notifyDelegateIfNeeded:(bool)arg4;
- (id)_contentFocusContainerGuide;
- (CGPoint)_contentOffsetForNewFrame:(CGRect)arg1 oldFrame:(CGRect)arg2 newContentSize:(CGSize)arg3 andOldContentSize:(CGSize)arg4;
- (id)_createPreparedCellForItemAtIndexPath:(id)arg1 withLayoutAttributes:(id)arg2 applyAttributes:(bool)arg3;
- (id)_createPreparedCellForItemAtIndexPath:(id)arg1 withLayoutAttributes:(id)arg2 applyAttributes:(bool)arg3 isFocused:(bool)arg4 notify:(bool)arg5;
- (id)_createPreparedSupplementaryViewForElementOfKind:(id)arg1 atIndexPath:(id)arg2 withLayoutAttributes:(id)arg3 applyAttributes:(bool)arg4;
- (id)_createTemplateLayoutCellForCellsWithIdentifier:(id)arg1;
- (id)_currentPromiseFulfillmentCell;
- (id)_currentTouch;
- (id)_currentUpdate;
- (bool)_dataSourceImplementsNumberOfSections;
- (bool)_dataSourceSupportsReordering;
- (UIEdgeInsets)_defaultLayoutMargins;
- (id)_delegatePreferredIndexPath;
- (CGPoint)_delegateTargetOffsetForProposedContentOffset:(CGPoint)arg1;
- (id)_dequeueReusableViewOfKind:(id)arg1 withIdentifier:(id)arg2 forIndexPath:(id)arg3 viewCategory:(NSUInteger)arg4;
- (void)_deselectAllAnimated:(bool)arg1 notifyDelegate:(bool)arg2;
- (void)_deselectItemAtIndexPath:(id)arg1 animated:(bool)arg2 notifyDelegate:(bool)arg3;
- (void)_didMoveFromWindow:(id)arg1 toWindow:(id)arg2;
- (void)_didScroll;
- (void)_didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (id)_doubleSidedAnimationsForView:(id)arg1 withStartingLayoutAttributes:(id)arg2 startingLayout:(id)arg3 endingLayoutAttributes:(id)arg4 endingLayout:(id)arg5 withAnimationSetup:(id /* block */)arg6 animationCompletion:(id /* block */)arg7 enableCustomAnimations:(bool)arg8 customAnimationsType:(NSUInteger)arg9;
- (id)_dynamicAnimationsForTrackValues;
- (void)_endItemAnimationsWithInvalidationContext:(id)arg1;
- (void)_endItemAnimationsWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2;
- (void)_endItemAnimationsWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2 animator:(id)arg3;
- (id)_endOfContentFocusContainerGuide;
- (void)_endReordering;
- (void)_endUpdatesWithInvalidationContext:(id)arg1 tentativelyForReordering:(bool)arg2 animator:(id)arg3;
- (void)_ensureViewsAreLoadedInRect:(CGRect)arg1;
- (void)_finishInteractiveTransitionShouldFinish:(bool)arg1 finalAnimation:(bool)arg2;
- (void)_finishInteractiveTransitionWithFinalAnimation:(bool)arg1;
- (id)_focusedCell;
- (id)_focusedCellElementKind;
- (id)_focusedCellIndexPath;
- (void)_focusedView:(id)arg1 isMinX:(bool*)arg2 isMaxX:(bool*)arg3 isMinY:(bool*)arg4 isMaxY:(bool*)arg5;
- (id)_fulfillPromisedFocusRegionForCell:(id)arg1;
- (void)_geometryChanges:(id)arg1 forAncestor:(id)arg2;
- (void)_getOriginalReorderingIndexPaths:(id*)arg1 targetIndexPaths:(id*)arg2;
- (bool)_hasContainerScrollViewsAndScrollingDisabled;
- (bool)_hasFocusedCellForIndexPath:(id)arg1 shouldUsePreUpdateData:(bool)arg2;
- (bool)_hasPrefetchItems;
- (bool)_hasRegisteredClassOrNibForSupplementaryViewOfKind:(id)arg1;
- (void)_highlightFirstVisibleItemIfAppropriate;
- (bool)_highlightItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(NSUInteger)arg3;
- (bool)_highlightItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(NSInteger)arg3 notifyDelegate:(bool)arg4;
- (id)_indexPathForCell:(id)arg1 includePrefetchedCells:(bool)arg2;
- (id)_indexPathForView:(id)arg1 ofType:(NSUInteger)arg2 includePrefetchedCells:(bool)arg3;
- (bool)_indexPathIsValid:(id)arg1;
- (id)_indexPathsForVisibleDecorationViewsOfKind:(id)arg1;
- (id)_indexPathsForVisibleSupplementaryViewsOfKind:(id)arg1;
- (id)_indexPathsForVisibleSupplementaryViewsOfKind:(id)arg1 isDecorationView:(bool)arg2;
- (void)_invalidateLayoutIfNecessaryForReload;
- (void)_invalidateLayoutWithContext:(id)arg1;
- (void)_invalidateWithBlock:(id /* block */)arg1;
- (bool)_isEditing;
- (bool)_isReordering;
- (bool)_isViewInReuseQueue:(id)arg1;
- (bool)_itemIndexPathIsReordered:(id)arg1;
- (bool)_keepsFirstResponderVisibleOnBoundsChange;
- (id)_keysForObject:(id)arg1 inDictionary:(id)arg2;
- (id)_managedSubviewForView:(id)arg1;
- (id)_managedViews;
- (id /* block */)_navigationCompletion;
- (id)_objectInDictionary:(id)arg1 forKind:(id)arg2 indexPath:(id)arg3;
- (void)_offsetPinnedReorderedItemsWithCurrentContentOffset:(CGPoint)arg1;
- (void)_performAction:(SEL)arg1 forCell:(id)arg2 sender:(id)arg3;
- (void)_performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2 invalidationContext:(id)arg3;
- (void)_performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2 invalidationContext:(id)arg3 tentativelyForReordering:(bool)arg4;
- (void)_performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2 invalidationContext:(id)arg3 tentativelyForReordering:(bool)arg4 animator:(id)arg5;
- (void)_performReloadPrefetchIfNeeded;
- (void)_pinReorderedItemsWithPinningTest:(id /* block */)arg1;
- (id)_pivotForTransitionFromLayout:(id)arg1 toLayout:(id)arg2;
- (id)_preReorderingIndexPathForLayoutIndexPath:(id)arg1;
- (NSUInteger)_prefetchItemsForVelocity:(struct CGVector { double x1; double x2; })arg1 maxItemsToPrefetch:(NSUInteger)arg2;
- (NSUInteger)_prefetchItemsForVelocity:(struct CGVector { double x1; double x2; })arg1 maxItemsToPrefetch:(NSUInteger)arg2 invalidateCandidatesOnDirectionChanges:(bool)arg3;
- (bool)_prefetchingEnabledDefault;
- (void)_prepareLayoutForUpdates;
- (void)_prepareViewForUse:(id)arg1 withElementCategory:(NSUInteger)arg2 elementKind:(id)arg3 reuseIdentifier:(id)arg4 indexPath:(id)arg5;
- (void)_prepareViewForUse:(id)arg1 withElementCategory:(NSUInteger)arg2 elementKind:(id)arg3 reuseIdentifier:(id)arg4 indexPath:(id)arg5 applyDefaultAttributes:(bool)arg6;
- (void)_pruneCachedPrefetchViewsForCacheValidationBounds:(CGRect)arg1;
- (void)_pruneCachedPrefetchViewsForVelocity:(struct CGVector { double x1; double x2; })arg1;
- (void)_registerForGeometryChangesIfInSupeview;
- (void)_registeredSupplementaryViewKind:(id)arg1;
- (void)_reloadDataIfNeeded;
- (bool)_remembersPreviouslyFocusedItem;
- (void)_removeAnyAncestorScrollViewNotifications;
- (void)_removeContainerScrollViewForNotifications:(id)arg1;
- (id)_reorderFeedbackBehavior;
- (id)_reorderPrefetchCandidates:(id)arg1 forPrefetchVelocity:(struct CGVector { double x1; double x2; })arg2 visibleBounds:(CGRect)arg3;
- (id)_reorderedItemForView:(id)arg1;
- (id)_reorderedItems;
- (CGPoint)_reorderingTargetPosition;
- (void)_resetContainerScrollViewVisitationCount;
- (void)_resetCurrentPrefetchContext;
- (void)_resetPrefetchState;
- (void)_resetPrefetchedCachedCells;
- (void)_resumeReloads;
- (void)_reuseCell:(id)arg1;
- (void)_reuseCell:(id)arg1 notifyDidEndDisplaying:(bool)arg2;
- (id)_reuseDictionaryForCell:(bool)arg1;
- (void)_reusePreviouslyFocusedManagedSubviewIfNeeded:(id)arg1;
- (id)_reuseQueueForViewWithElementCategory:(NSUInteger)arg1 elementKind:(id)arg2 reuseIdentifier:(id)arg3;
- (void)_reuseSupplementaryView:(id)arg1;
- (void)_scrollFirstResponderCellToVisible:(bool)arg1;
- (void)_scrollViewDidEndDraggingWithDeceleration:(bool)arg1;
- (void)_scrollViewWillEndDraggingWithVelocity:(CGPoint)arg1 targetContentOffset:(inout CGPoint*)arg2;
- (void)_selectAllSelectedItems;
- (void)_selectItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(NSUInteger)arg3 notifyDelegate:(bool)arg4;
- (id)_selectableIndexPathForItemContainingHitView:(id)arg1;
- (void)_setAllowsMultipleSelectionDuringEditing:(bool)arg1;
- (void)_setAllowsSelectionDuringEditing:(bool)arg1;
- (void)_setCellPrefetchMode:(NSInteger)arg1;
- (void)_setCollectionViewLayout:(id)arg1 animated:(bool)arg2 isInteractive:(bool)arg3 completion:(id /* block */)arg4;
- (void)_setCollectionViewLayout:(id)arg1 animated:(bool)arg2 isInteractive:(bool)arg3 completion:(id /* block */)arg4 animator:(id)arg5;
- (void)_setCurrentPromiseFulfillmentCell:(id)arg1;
- (void)_setCurrentTouch:(id)arg1;
- (void)_setDefaultLayoutMargins:(UIEdgeInsets)arg1;
- (void)_setExternalObjectTable:(id)arg1 forNibLoadingOfCellWithReuseIdentifier:(id)arg2;
- (void)_setExternalObjectTable:(id)arg1 forNibLoadingOfSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)_setFocusedCell:(id)arg1;
- (void)_setFocusedCellElementKind:(id)arg1;
- (void)_setFocusedCellIndexPath:(id)arg1;
- (void)_setIsAncestorOfFirstResponder:(bool)arg1;
- (void)_setKeepsFirstResponderVisibleOnBoundsChange:(bool)arg1;
- (void)_setNavigationCompletion:(id /* block */)arg1;
- (void)_setNeedsVisibleCellsUpdate:(bool)arg1 withLayoutAttributes:(bool)arg2;
- (void)_setObject:(id)arg1 inDictionary:(id)arg2 forKind:(id)arg3 indexPath:(id)arg4;
- (void)_setRemembersPreviouslyFocusedItem:(bool)arg1;
- (void)_setReorderFeedbackBehavior:(id)arg1;
- (void)_setShouldDeriveVisibleBoundsFromContainingScrollView:(bool)arg1;
- (void)_setShouldPrefetchCellsWhenPerformingReloadData:(bool)arg1;
- (void)_setVisibleView:(id)arg1 forLayoutAttributes:(id)arg2;
- (void)_setupCellAnimations;
- (bool)_shouldDeriveVisibleBoundsFromContainingScrollView;
- (bool)_shouldFadeCellsForBoundChangeWhileRotating;
- (bool)_shouldPrefetchCells;
- (bool)_shouldPrefetchCellsWhenPerformingReloadData;
- (bool)_shouldScrollToContentBeginningInRightToLeft;
- (bool)_shouldShowMenuForCell:(id)arg1;
- (bool)_shouldUpdateFocusInContext:(id)arg1;
- (void)_stopAutoscrollTimer;
- (void)_suspendReloads;
- (id)_templateLayoutCellForCellsWithReuseIdentifier:(id)arg1;
- (void)_trackLayoutValue:(double)arg1 forKey:(id)arg2;
- (double)_trackedLayoutValueForKey:(id)arg1;
- (void)_unhighlightAllItems;
- (void)_unhighlightAllItemsAndHighlightGlobalItem:(NSInteger)arg1;
- (void)_unhighlightItemAtIndexPath:(id)arg1 animated:(bool)arg2;
- (void)_unhighlightItemAtIndexPath:(id)arg1 animated:(bool)arg2 notifyDelegate:(bool)arg3;
- (CGVector)_unitVectorForVector:(CGVector)arg1;
- (void)_unpinReorderedItemsIfNeeded;
- (void)_updateAnimationDidStop:(id)arg1 finished:(id)arg2 context:(id)arg3;
- (void)_updateBackgroundView;
- (void)_updateContainerScrollViewsForNotifications;
- (void)_updateContentFocusContainerGuides;
- (void)_updateDefaultLayoutMargins;
- (void)_updateEditing:(bool)arg1 forView:(id)arg2 atIndexPath:(id)arg3;
- (void)_updateFocusedCellIndexPathIfNecessaryWithLastFocusedRect:(CGRect)arg1;
- (void)_updateReorderingTargetPosition:(CGPoint)arg1;
- (void)_updateReorderingTargetPosition:(CGPoint)arg1 forced:(bool)arg2;
- (void)_updateRowsAtIndexPaths:(id)arg1 updateAction:(int)arg2;
- (void)_updateSections:(id)arg1 updateAction:(int)arg2;
- (void)_updateTrackedLayoutValuesWith:(id)arg1;
- (void)_updateTransitionWithProgress:(double)arg1;
- (NSUInteger)_updateVisibleCellsNow:(bool)arg1;
- (void)_updateWithItems:(id)arg1 tentativelyForReordering:(bool)arg2 animator:(id)arg3;
- (void)_userSelectItemAtIndexPath:(id)arg1;
- (id)_viewAnimationsForCurrentUpdate;
- (id)_viewControllerToNotifyOnLayoutSubviews;
- (bool)_viewIsReorderedCell:(id)arg1;
- (bool)_visible;
- (CGRect)_visibleBounds;
- (id)_visibleCellForIndexPath:(id)arg1;
- (id)_visibleDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)_visibleDecorationViewsOfKind:(id)arg1;
- (id)_visibleSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)_visibleSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2 isDecorationView:(bool)arg3;
- (id)_visibleSupplementaryViewsOfKind:(id)arg1;
- (id)_visibleSupplementaryViewsOfKind:(id)arg1 isDecorationView:(bool)arg2;
- (id)_visibleViewDictForElementCategory:(NSUInteger)arg1 elementKind:(id)arg2;
- (id)_visibleViewForLayoutAttributes:(id)arg1;
- (id)_visibleViews;
- (bool)allowsMultipleSelection;
- (bool)allowsSelection;
- (id)backgroundView;
- (bool)beginInteractiveMovementForItemAtIndexPath:(id)arg1;
- (bool)canBeEdited;
- (bool)canBecomeFirstResponder;
- (bool)canBecomeFocused;
- (void)cancelInteractiveMovement;
- (void)cancelInteractiveTransition;
- (id)cellForItemAtIndexPath:(id)arg1;
- (id)collectionViewLayout;
//- (id)dataSource;
- (void)dealloc;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)deleteItemsAtIndexPaths:(id)arg1;
- (void)deleteSections:(id)arg1;
- (id)dequeueReusableCellWithReuseIdentifier:(id)arg1 forIndexPath:(id)arg2;
- (id)dequeueReusableSupplementaryViewOfKind:(id)arg1 withReuseIdentifier:(id)arg2 forIndexPath:(id)arg3;
- (id)description;
- (void)deselectItemAtIndexPath:(id)arg1 animated:(bool)arg2;
- (void)didMoveToWindow;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)endInteractiveMovement;
- (void)finishInteractiveTransition;
- (NSInteger)highlightedGlobalItem;
- (id)indexPathForCell:(id)arg1;
- (id)indexPathForItemAtPoint:(CGPoint)arg1;
- (id)indexPathForSupplementaryView:(id)arg1;
//- (id)indexPathsForSelectedItems;
- (id)indexPathsForVisibleItems;
- (id)indexPathsForVisibleSupplementaryElementsOfKind:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(CGRect)arg1;
- (id)initWithFrame:(CGRect)arg1 collectionViewLayout:(id)arg2;
- (void)insertItemsAtIndexPaths:(id)arg1;
- (void)insertSections:(id)arg1;
- (CGSize)intrinsicContentSize;
- (bool)isEditing;
- (bool)isPrefetchingEnabled;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (void)layoutSubviews;
- (NSInteger)maximumGlobalItemIndex;
- (void)moveItemAtIndexPath:(id)arg1 toIndexPath:(id)arg2;
- (void)moveSection:(NSInteger)arg1 toSection:(NSInteger)arg2;
- (NSInteger)numberOfItemsInSection:(NSInteger)arg1;
- (NSInteger)numberOfSections;
- (void)performBatchUpdates:(id /* block */)arg1 completion:(id /* block */)arg2;
- (void)performBatchUpdates:(id /* block */)arg1 withAnimator:(id)arg2;
- (id)preferredFocusedItem;
- (void)prefetchCompleteForItemAtIndexPath:(id)arg1;
- (id)prefetchDataSource;
- (id)preparedCells;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;
- (void)registerClass:(Class)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)registerClass:(Class)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)registerNib:(id)arg1 forCellWithReuseIdentifier:(id)arg2;
- (void)registerNib:(id)arg1 forSupplementaryViewOfKind:(id)arg2 withReuseIdentifier:(id)arg3;
- (void)reloadData;
- (void)reloadItemsAtIndexPaths:(id)arg1;
- (void)reloadSections:(id)arg1;
- (bool)remembersLastFocusedIndexPath;
- (void)scrollToItemAtIndexPath:(id)arg1 atScrollPosition:(NSUInteger)arg2 animated:(bool)arg3;
- (void)selectItemAtIndexPath:(id)arg1 animated:(bool)arg2 scrollPosition:(NSUInteger)arg3;
- (void)setAllowsMultipleSelection:(bool)arg1;
- (void)setAllowsSelection:(bool)arg1;
- (void)setBackgroundView:(id)arg1;
- (void)setBounds:(CGRect)arg1;
- (void)setCollectionViewLayout:(id)arg1;
- (void)setCollectionViewLayout:(id)arg1 animated:(bool)arg2;
- (void)setCollectionViewLayout:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)setCollectionViewLayout:(id)arg1 withAnimator:(id)arg2;
- (void)setContentInset:(UIEdgeInsets)arg1;
- (void)setContentOffset:(CGPoint)arg1 animated:(bool)arg2;
- (void)setContentSize:(CGSize)arg1;
- (void)setDataSource:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setEditing:(bool)arg1;
- (void)setFrame:(CGRect)arg1;
- (void)setLayoutMargins:(UIEdgeInsets)arg1;
- (void)setPrefetchDataSource:(id)arg1;
- (void)setPrefetchingEnabled:(bool)arg1;
- (void)setRemembersLastFocusedIndexPath:(bool)arg1;
- (void)setScrollEnabled:(bool)arg1;
- (void)setSemanticContentAttribute:(NSInteger)arg1;
- (id)startInteractiveTransitionToCollectionViewLayout:(id)arg1 completion:(id /* block */)arg2;
- (id)supplementaryViewForElementKind:(id)arg1 atIndexPath:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateInteractiveMovementTargetPosition:(CGPoint)arg1;
- (NSArray<__kindof RDCollectionViewCell *> *)visibleCells;
- (NSArray<RDCollectionReusableView *> *)visibleSupplementaryViewsOfKind:(NSString *)elementKind;


@end
